from io import StringIO
from pathlib import Path

from alembic import command
from alembic.config import Config
from sqlalchemy import create_engine, inspect, text


def config():
    return Config(str(Path(__file__).resolve().parents[1] / "alembic.ini"))


def test_upgrade_empty_database_and_roundtrip_preserves_users():
    engine = create_engine("sqlite://")
    with engine.connect() as connection:
        cfg = config()
        cfg.attributes["connection"] = connection
        command.upgrade(cfg, "head")
        columns = {c["name"]: c for c in inspect(connection).get_columns("users")}
        assert set(columns) == {"id", "name", "email", "password"}
        assert columns["password"]["nullable"] is False
        connection.execute(text("INSERT INTO users (name, email, password) VALUES (:n, :e, :p)"),
                           {"n": "Alice", "e": "alice@example.com", "p": "hashed-password"})
        connection.commit()
        command.downgrade(cfg, "b001_initial_users")
        columns = {c["name"]: c for c in inspect(connection).get_columns("users")}
        assert columns["password"]["nullable"] is True
        command.upgrade(cfg, "head")
        assert connection.scalar(text("SELECT count(*) FROM users")) == 1
        assert connection.scalar(text("SELECT password FROM users")) == "hashed-password"
    engine.dispose()


def test_existing_stamped_database_is_preserved():
    engine = create_engine("sqlite://")
    with engine.connect() as connection:
        connection.execute(text("CREATE TABLE users (id INTEGER PRIMARY KEY, name VARCHAR(100) NOT NULL, "
                                "email VARCHAR(150) NOT NULL UNIQUE, password VARCHAR(255) NOT NULL)"))
        connection.execute(text("INSERT INTO users VALUES (1, 'Alice', 'alice@example.com', 'hashed')"))
        connection.commit()
        cfg = config()
        cfg.attributes["connection"] = connection
        command.stamp(cfg, "a37a2056e593")
        command.upgrade(cfg, "head")
        assert connection.scalar(text("SELECT password FROM users WHERE id = 1")) == "hashed"
    engine.dispose()


def test_oracle_offline_sql(monkeypatch):
    import database
    from sqlalchemy.engine import make_url

    monkeypatch.setattr(database, "DATABASE_URL", make_url("oracle+oracledb://"))
    output = StringIO()
    cfg = config()
    cfg.output_buffer = output
    command.upgrade(cfg, "head", sql=True)
    sql = output.getvalue()
    assert "CREATE TABLE users" in sql
    assert "GENERATED BY DEFAULT AS IDENTITY" in sql
    assert "ALTER TABLE users MODIFY password NOT NULL" in sql
