from io import StringIO
from pathlib import Path

from alembic import command
from alembic.config import Config
from sqlalchemy import create_engine, inspect, text


def config():
    return Config(str(Path(__file__).resolve().parents[1] / "alembic.ini"))


def test_upgrade_empty_database_and_roundtrip_preserves_users():
    engine = create_engine("sqlite://")
    with engine.connect() as connection:
        cfg = config()
        cfg.attributes["connection"] = connection
        command.upgrade(cfg, "a37a2056e593")
        columns = {c["name"]: c for c in inspect(connection).get_columns("users")}
        assert set(columns) == {"id", "name", "email", "password"}
        assert columns["password"]["nullable"] is False
        connection.execute(text("INSERT INTO users (name, email, password) VALUES (:n, :e, :p)"),
                           {"n": "Alice", "e": "alice@example.com", "p": "hashed-password"})
        connection.commit()
        command.downgrade(cfg, "b001_initial_users")
        columns = {c["name"]: c for c in inspect(connection).get_columns("users")}
        assert columns["password"]["nullable"] is True
        command.upgrade(cfg, "head")
        assert connection.scalar(text("SELECT count(*) FROM users")) == 1
        assert connection.scalar(text("SELECT password_hash FROM users")) == "hashed-password"
        assert connection.scalar(text("SELECT first_name FROM users")) == "Alice"
        assert connection.scalar(text("SELECT last_name FROM users")) is None
        assert connection.scalar(text("SELECT role FROM users")) == "USER"
        assert connection.scalar(text("SELECT is_active FROM users")) == 1
        command.downgrade(cfg, "a37a2056e593")
        assert connection.scalar(text("SELECT password FROM users")) == "hashed-password"
        command.upgrade(cfg, "head")
    engine.dispose()


def test_existing_stamped_database_is_preserved():
    engine = create_engine("sqlite://")
    with engine.connect() as connection:
        connection.execute(text("CREATE TABLE users (id INTEGER PRIMARY KEY, name VARCHAR(100) NOT NULL, "
                                "email VARCHAR(150) NOT NULL UNIQUE, password VARCHAR(255) NOT NULL)"))
        connection.execute(text("INSERT INTO users VALUES (1, 'Alice', 'alice@example.com', 'hashed')"))
        connection.commit()
        cfg = config()
        cfg.attributes["connection"] = connection
        command.stamp(cfg, "a37a2056e593")
        command.upgrade(cfg, "head")
        assert connection.scalar(text("SELECT password_hash FROM users WHERE id = 1")) == "hashed"
        assert connection.scalar(text("SELECT first_name FROM users WHERE id = 1")) == "Alice"
    engine.dispose()


def test_oracle_offline_sql(monkeypatch):
    import database
    from sqlalchemy.engine import make_url

    monkeypatch.setattr(database, "DATABASE_URL", make_url("oracle+oracledb://"))
    output = StringIO()
    cfg = config()
    cfg.output_buffer = output
    command.upgrade(cfg, "head", sql=True)
    sql = output.getvalue()
    assert "CREATE TABLE users" in sql
    assert "GENERATED BY DEFAULT AS IDENTITY" in sql
    assert "ALTER TABLE users MODIFY password NOT NULL" in sql
    assert "RENAME COLUMN name TO first_name" in sql
    assert "RENAME COLUMN password TO password_hash" in sql
    assert "ck_users_role" in sql
    assert "CREATE TABLE authors" in sql
    assert "CREATE TABLE books" in sql
    assert "CREATE TABLE book_authors" in sql
    assert "CREATE TABLE book_copies" in sql


def test_catalogue_migration_and_downgrade_keep_users():
    engine = create_engine('sqlite://')
    with engine.connect() as connection:
        cfg = config()
        cfg.attributes['connection'] = connection
        command.upgrade(cfg, 'u002_user_management')
        connection.execute(text("INSERT INTO users (first_name, email, password_hash) VALUES ('Alice', 'alice@example.com', 'hashed')"))
        connection.commit()
        command.upgrade(cfg, 'head')
        inspector = inspect(connection)
        assert {'authors', 'books', 'book_authors', 'book_copies'} <= set(inspector.get_table_names())
        assert len(inspector.get_foreign_keys('book_authors')) == 2
        assert len(inspector.get_foreign_keys('book_copies')) == 1
        command.downgrade(cfg, 'u002_user_management')
        assert 'books' not in inspect(connection).get_table_names()
        assert connection.scalar(text('SELECT password_hash FROM users')) == 'hashed'
    engine.dispose()
